### ISSUE TITLE
[Feature]: Cyrillic Lang enc.

### ISSUE THREAD

**Issue by VirusNik21** [bushvin/actor-export#13]
### Summary

Great work, but in all likelihood the module doesn't recognize Cyrillic and doesn't output the inscriptions in it. For example, Russian letters. Perhaps support for the required encoding has not been added (UTF-8, Windows-1251, CP-866, KOI-8R, ISO-8859-5)?
In the final file there are spaces instead of Russian letters.

**Comment by bushvin** [comment]
The module, IMO, is not the issue, as it used whatever encoding the browser is using.

The font itself has no Cyrillic characters. Alternatively, I could fall back to Helvetica. But that will require a rework, for wich I have no time right now. Somewhere September is doable.

**Comment by bushvin** [comment]
The update is available with release 2024.11.3
