### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Geluxu** [bushvin/actor-export#6]
### Contact Details

geluxrolero@gmail.com

### Foundry VTT version

11.315

### Game system

pf2e

### Game system version

5.14.4

### actor-export module version

Latest

### What browsers are you seeing the problem on?

Chrome

### What Provider is affected?

PF2e Remaster Character sheet, PF2e Scribe Generator

### What happened?

The following error message appears when I try to export an actor 

![image](https://github.com/bushvin/actor-export/assets/164147153/e16861d8-0c67-402c-9379-83bb76ff2ce1)

And it stays like this

**Comment by Geluxu** [comment]
Just Realized that the module Only works with  actual Player Characters. Any chances that this will work for NPC sheets in the future?

**Comment by bushvin** [comment]
Hello @Geluxu ,

The scribe provider has some room for improvement.

Would you be able to tell me if it is an existing NPC from any of the packs, or if it is a custom one?

If it is a custom one, could you export it, and attach it to this bug?

I will check what is needed to update it.

**Comment by Geluxu** [comment]
Plese find the Json attached 
[fvtt-Actor-rathian-Jd9ILwJeOOgBi9pX.json](https://github.com/bushvin/actor-export/files/14692880/fvtt-Actor-rathian-Jd9ILwJeOOgBi9pX.json)

**Comment by bushvin** [comment]
Should be resolved in 2024.3.2

**Comment by bushvin** [comment]
Since I haven't heard back, and it works on my environment with your actor, I'm considering this resolved.
Feel free to reopen, if it is not!
