### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by spookymonster** [bushvin/actor-export#7]
### Contact Details

spookymonster@gmail.com

### Foundry VTT version

11.315

### Game system

pf2e

### Game system version

5.15.0

### actor-export module version

2024.4.1

### What browsers are you seeing the problem on?

Microsoft Edge

### What Provider is affected?

PF2e Remaster Character sheet

### What happened?

Bushvin remastered charsheet has overtyped characters in action block (see screenshot). This appears to be a bug in the charsheet, not the module itself.

### Attachments

![image](https://github.com/bushvin/actor-export/assets/16195156/18df357d-c8e4-4500-9ddb-f9f897715e10)

**Comment by bushvin** [comment]
Should be fixed with [d26e42b](https://github.com/bushvin/actor-export/commit/d26e42b781ef5613f91bd07052315bfce3a5f44e).
Released in 2024.4.2
Happy gaming!
