### ISSUE TITLE
[Bug]: 5e "CharacterDetails" is scrambled.

### ISSUE THREAD

**Issue by BDimi** [bushvin/actor-export#8]
### Foundry VTT version

11.315

### Game system

dnd5e

### Game system version

3.1.2

### actor-export module version

2024.4.6

### What Provider is affected?

Dungeons & Dragons 5th edition Character sheets

### What happened?

When exporting all "D&D 5e Character Sheet", "D&D 5e Character Details Sheet", & "D&D 5e Character Spellcasting Sheet", the details sheet ends up with scrambled text on the page. The words all seem to go in the correct spots, but it looks like they've been hit with ROT13 or something.

**Comment by bushvin** [comment]
That is weird, this happened to me once as well, but I could not reproduce it. After completely reloading it didn't happen again.

Would you mind telling me more about your setup?

What pdf viewer do you use, which version?

What browser are you using, which version?

What os are you running, which version?

**Comment by bushvin** [comment]
also, would you mind sharing an export of your character, and possibly the resulting PDF?

**Comment by BDimi** [comment]
[fvtt-Actor-demo-player-FW8KpUvniufCDeFZ.json](https://github.com/bushvin/actor-export/files/15177922/fvtt-Actor-demo-player-FW8KpUvniufCDeFZ.json)
[Demo Player - CharacterSheet.pdf](https://github.com/bushvin/actor-export/files/15177923/Demo.Player.-.CharacterSheet.pdf)
[Demo Player - CharacterDetails.pdf](https://github.com/bushvin/actor-export/files/15177926/Demo.Player.-.CharacterDetails.pdf)

I reproduced the problem with 6 different characters and then rolled this new one with SRD data. If I only select Details, then the sheet comes out correctly.

- I have a bunch of modules enabled (54 including Actor Export), so I won't name them all unless you think you need it.
- I'm using Foxit PDF reader, but the problem occurs with other PDF readers, including the ones built into Firefox, Edge, etc.
- I'm running Foundry locally, so not using any browser besides what Foundry has natively.
- Windows 10. Latest patches.

**Comment by bushvin** [comment]
@BDimi I think I discovered why this happens, but I'm not 100% sure, as I cannot reliably reproduce the problem.

Could you please confirm if release `2024.5.1` fixes the issue?

**Comment by BDimi** [comment]
No, same result.
![image](https://github.com/bushvin/actor-export/assets/120278747/5d22bee1-7d4c-496b-b33a-6954297126cc)

**Comment by bushvin** [comment]
Drat... Double drat...

Could you also provide the feedback from your browser console?

Developer tools >> console

**Comment by BDimi** [comment]
I think this is the relevant content:
![image](https://github.com/bushvin/actor-export/assets/120278747/b106a780-f1b8-4938-83ec-600408b78023)

**Comment by bushvin** [comment]
It is indeed the relevant section.

How many pdfs did you try to export in this case?
The reason I ask is because the errors do not show the entire path `export...f`

If you could copy the paths, that would be awesome.

**Comment by BDimi** [comment]
Three PDF's: basic, details, spellcasting.
First URL: http://localhost:30000/modules/actor-export/providers/dnd5e/fonts/MarkerFelt.ttf?t=1714668792709
Second: http://localhost:30000/modules/actor-export/providers/dnd5e/fonts/MarkerFelt.ttf?t=1714668792724

**Comment by bushvin** [comment]
That is the problem. You exported 3 pdfs, you should have had 3 errors.

The reason you get the error is because it looks for the specified font in 2 directories, prioritising the one closest to the provider.

Let me investigate further.

**Comment by bushvin** [comment]
I think now I got to the bottom of it. One of my objects to control the embedding of the text was not properly deep cloned.

Can you retry with 2024.5.2?

**Comment by BDimi** [comment]
Yeah, that did it! Thanks!
